# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Keithley_2400Gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(683, 226)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(140, 10, 501, 201))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Config = QtGui.QWidget()
        self.Config.setObjectName(_fromUtf8("Config"))
        self.gpibAddrInputBox = QtGui.QLineEdit(self.Config)
        self.gpibAddrInputBox.setGeometry(QtCore.QRect(50, 20, 51, 20))
        self.gpibAddrInputBox.setObjectName(_fromUtf8("gpibAddrInputBox"))
        self.pushButton = QtGui.QPushButton(self.Config)
        self.pushButton.setGeometry(QtCore.QRect(400, 140, 71, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.connectButton = QtGui.QPushButton(self.Config)
        self.connectButton.setGeometry(QtCore.QRect(0, 60, 110, 32))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.label_3 = QtGui.QLabel(self.Config)
        self.label_3.setGeometry(QtCore.QRect(10, 25, 56, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.sourSelect = QtGui.QGroupBox(self.Config)
        self.sourSelect.setGeometry(QtCore.QRect(130, 10, 91, 91))
        self.sourSelect.setObjectName(_fromUtf8("sourSelect"))
        self.sourVolt = QtGui.QRadioButton(self.sourSelect)
        self.sourVolt.setGeometry(QtCore.QRect(0, 20, 97, 18))
        self.sourVolt.setObjectName(_fromUtf8("sourVolt"))
        self.sourCurr = QtGui.QRadioButton(self.sourSelect)
        self.sourCurr.setGeometry(QtCore.QRect(0, 50, 97, 18))
        self.sourCurr.setObjectName(_fromUtf8("sourCurr"))
        self.outputSelect = QtGui.QPushButton(self.Config)
        self.outputSelect.setGeometry(QtCore.QRect(0, 140, 110, 32))
        self.outputSelect.setObjectName(_fromUtf8("outputSelect"))
        self.tabWidget.addTab(self.Config, _fromUtf8(""))
        self.Control = QtGui.QWidget()
        self.Control.setObjectName(_fromUtf8("Control"))
        self.settingValue = QtGui.QLineEdit(self.Control)
        self.settingValue.setGeometry(QtCore.QRect(60, 27, 113, 21))
        self.settingValue.setObjectName(_fromUtf8("settingValue"))
        self.settingValueLabel = QtGui.QLabel(self.Control)
        self.settingValueLabel.setGeometry(QtCore.QRect(10, 30, 56, 13))
        self.settingValueLabel.setObjectName(_fromUtf8("settingValueLabel"))
        self.settingUnit = QtGui.QLabel(self.Control)
        self.settingUnit.setGeometry(QtCore.QRect(180, 30, 56, 13))
        self.settingUnit.setObjectName(_fromUtf8("settingUnit"))
        self.groupBox = QtGui.QGroupBox(self.Control)
        self.groupBox.setGeometry(QtCore.QRect(0, 60, 321, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.fastSelect = QtGui.QRadioButton(self.groupBox)
        self.fastSelect.setGeometry(QtCore.QRect(10, 50, 97, 18))
        self.fastSelect.setObjectName(_fromUtf8("fastSelect"))
        self.slowSelect = QtGui.QRadioButton(self.groupBox)
        self.slowSelect.setGeometry(QtCore.QRect(10, 80, 97, 18))
        self.slowSelect.setObjectName(_fromUtf8("slowSelect"))
        self.jumpSelect = QtGui.QRadioButton(self.groupBox)
        self.jumpSelect.setGeometry(QtCore.QRect(240, 80, 97, 18))
        self.jumpSelect.setObjectName(_fromUtf8("jumpSelect"))
        self.accerFast = QtGui.QLineEdit(self.groupBox)
        self.accerFast.setGeometry(QtCore.QRect(110, 50, 61, 21))
        self.accerFast.setObjectName(_fromUtf8("accerFast"))
        self.accerSlow = QtGui.QLineEdit(self.groupBox)
        self.accerSlow.setGeometry(QtCore.QRect(110, 80, 61, 21))
        self.accerSlow.setObjectName(_fromUtf8("accerSlow"))
        self.accerUnit = QtGui.QLabel(self.groupBox)
        self.accerUnit.setGeometry(QtCore.QRect(190, 70, 56, 13))
        self.accerUnit.setObjectName(_fromUtf8("accerUnit"))
        self.scannerCancel = QtGui.QPushButton(self.Control)
        self.scannerCancel.setGeometry(QtCore.QRect(370, 140, 110, 32))
        self.scannerCancel.setObjectName(_fromUtf8("scannerCancel"))
        self.scannerStart = QtGui.QPushButton(self.Control)
        self.scannerStart.setGeometry(QtCore.QRect(370, 80, 110, 32))
        self.scannerStart.setObjectName(_fromUtf8("scannerStart"))
        self.nowWriteOutputBox = QtGui.QLineEdit(self.Control)
        self.nowWriteOutputBox.setGeometry(QtCore.QRect(230, 30, 113, 21))
        self.nowWriteOutputBox.setReadOnly(True)
        self.nowWriteOutputBox.setObjectName(_fromUtf8("nowWriteOutputBox"))
        self.tabWidget.addTab(self.Control, _fromUtf8(""))
        self.Display = QtGui.QWidget()
        self.Display.setObjectName(_fromUtf8("Display"))
        self.tabWidget.addTab(self.Display, _fromUtf8(""))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 56, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 56, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.voltDisp = QtGui.QLabel(Form)
        self.voltDisp.setGeometry(QtCore.QRect(30, 40, 131, 16))
        self.voltDisp.setObjectName(_fromUtf8("voltDisp"))
        self.currDisp = QtGui.QLabel(Form)
        self.currDisp.setGeometry(QtCore.QRect(30, 100, 131, 16))
        self.currDisp.setObjectName(_fromUtf8("currDisp"))
        self.outputStatsDisp = QtGui.QLabel(Form)
        self.outputStatsDisp.setGeometry(QtCore.QRect(20, 150, 71, 16))
        self.outputStatsDisp.setObjectName(_fromUtf8("outputStatsDisp"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton.setText(_translate("Form", "Reset", None))
        self.connectButton.setText(_translate("Form", "Connect", None))
        self.label_3.setText(_translate("Form", "GPIB:", None))
        self.sourSelect.setTitle(_translate("Form", "Source", None))
        self.sourVolt.setText(_translate("Form", "Voltage", None))
        self.sourCurr.setText(_translate("Form", "Current", None))
        self.outputSelect.setText(_translate("Form", "Ouput", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Config), _translate("Form", "Config", None))
        self.settingValueLabel.setText(_translate("Form", "Setting", None))
        self.settingUnit.setText(_translate("Form", "V", None))
        self.groupBox.setTitle(_translate("Form", "Scanning rate", None))
        self.fastSelect.setText(_translate("Form", "Fast", None))
        self.slowSelect.setText(_translate("Form", "Slow", None))
        self.jumpSelect.setText(_translate("Form", "Jump", None))
        self.accerUnit.setText(_translate("Form", "V/s", None))
        self.scannerCancel.setText(_translate("Form", "Cancel", None))
        self.scannerStart.setText(_translate("Form", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Control), _translate("Form", "Control", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Display), _translate("Form", "Display", None))
        self.label.setText(_translate("Form", "Voltage:", None))
        self.label_2.setText(_translate("Form", "Current:", None))
        self.voltDisp.setText(_translate("Form", "0.0", None))
        self.currDisp.setText(_translate("Form", "0.0", None))
        self.outputStatsDisp.setText(_translate("Form", "Output:", None))

